### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by Rahul3105** [anuragg0107/freezing-roll-5661#23]

**Comment by Rahul3105** [comment]
In the News section cards have different height, height width and overall design of all card should be same.
![Screenshot 2023-01-21 at 12 58 21 AM](https://user-images.githubusercontent.com/79327383/213788839-3167ad76-46b9-441a-8658-fc075d735a0c.png)

**Comment by Rahul3105** [comment]
Shop by category section alignment is not in center
<img width="1508" alt="Screenshot 2023-01-21 at 1 02 51 AM" src="https://user-images.githubusercontent.com/79327383/213790108-9e2821d8-6255-48e2-85bf-20c867b0304e.png">

**Comment by Rahul3105** [comment]
Due to some frontend bug, it's calling be api every millisecond, go to the hosted link and open network tab to see
![Screenshot 2023-01-21 at 1 05 23 AM](https://user-images.githubusercontent.com/79327383/213790490-346c5011-d537-4f83-b348-6d4eedd4d05e.png)

**Comment by Rahul3105** [comment]
On Add to cart, api is throwing 500 error
![Screenshot 2023-01-21 at 1 08 29 AM](https://user-images.githubusercontent.com/79327383/213790944-7a7ea98a-fa58-47e3-abab-66483feee7b0.png)

**Comment by Rahul3105** [comment]
Card alignment really needs improvement
![Screenshot 2023-01-21 at 1 09 40 AM](https://user-images.githubusercontent.com/79327383/213791123-49bfd697-1ccd-4e83-be13-54a92ecf0e36.png)

**Comment by Rahul3105** [comment]
When i select any filtering checkbox on chicken page, it's making some api call 3 times
![Screenshot 2023-01-21 at 1 11 23 AM](https://user-images.githubusercontent.com/79327383/213791461-4bb0770f-4352-4313-974a-91cba4b14d7e.png)

**Comment by Rahul3105** [comment]
Font used in checkout page is really very bad 
![Screenshot 2023-01-21 at 1 13 05 AM](https://user-images.githubusercontent.com/79327383/213791962-4e0ea31b-0bed-4b68-808a-c4d57fff0696.png)

**Comment by Rahul3105** [comment]
Product component is a complete mess right now... 
1. same comported 4 times
2. used meaningless classname
3. contains syntax errors, didn't use chakra
![Screenshot 2023-01-21 at 1 18 30 AM](https://user-images.githubusercontent.com/79327383/213792981-461088db-08a9-4fbe-8f4e-8233fcdb09f8.png)
![Screenshot 2023-01-21 at 1 18 09 AM](https://user-images.githubusercontent.com/79327383/213792989-d5e50333-00c0-4d73-8d84-413405660ac8.png)
![Screenshot 2023-01-21 at 1 17 43 AM](https://user-images.githubusercontent.com/79327383/213792998-bc873908-29f2-46f6-92a7-a6fea7d9093f.png)

**Comment by Rahul3105** [comment]
OTP functionality is completely hardcoded
![Screenshot 2023-01-21 at 1 24 11 AM](https://user-images.githubusercontent.com/79327383/213793717-e2a43dd6-31b6-4829-97fb-329dea13a30a.png)

**Comment by Harshank11** [comment]
All Done, Fixed and Resolved
